import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import { cn } from "@/lib/utils";

const font = Poppins({
  weight: ["600"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(`antialiased `, font.className)}>{children}</body>
    </html>
  );
}
// bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-primary to-secondary
